package io.mycat.plan.common;

public enum CastTarget {
	ITEM_CAST_BINARY,
	ITEM_CAST_CHAR,  
	ITEM_CAST_DATE,
	ITEM_CAST_DATETIME, 
	ITEM_CAST_DECIMAL, 
	//JSON
	ITEM_CAST_NCHAR,  
	ITEM_CAST_SIGNED_INT, 
	ITEM_CAST_TIME, 
	ITEM_CAST_UNSIGNED_INT;
}
