version: '2'
networks:
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.253
services:
    mysql1:
        image: mysql:5.7
        container_name: backend-mysql1
        hostname: backend-mysql1
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "33061:3306"
        networks:
            net:
              ipv4_address: 172.18.0.2
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    mysql2:
        image: mysql:5.7
        container_name: backend-mysql2
        hostname: backend-mysql2
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "33062:3306"
        networks:
            net:
              ipv4_address: 172.18.0.3
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    OBsharding-D-server:
        image: oceanbase/OBsharding-D:latest
        container_name: OBsharding-D-server
        hostname: OBsharding-D-server
        privileged: true
        stdin_open: true
        tty: true
        command: ["/opt/OBsharding-D/bin/wait-for-it.sh", "backend-mysql1:3306","--","/opt/OBsharding-D/bin/docker_init_start.sh"]
        ports:
            - "8066:8066"
            - "9066:9066"
        depends_on:
            - "mysql1"
            - "mysql2"
        networks:
            net:
              ipv4_address: 172.18.0.5