From centos:centos7
RUN yum install -y wget java mysql python3 python3-devel pip3 mysql-devel gcc && \
    yum clean all && rm -rf /var/cache/yum/*

# to https://github.com/actiontech/dble/releases get latest package download locally
COPY dble-3.20.07.0-20200831034733-linux.tar.gz /opt/

RUN tar zxvf /opt/dble-3.20.07.0-20200831034733-linux.tar.gz -C /opt && \
    rm -f /opt/dble-3.20.07.0-20200831034733-linux.tar.gz && \
    pip3 install mysqlclient -i http://pypi.douban.com/simple --trusted-host pypi.douban.com && \
    pip3 install six -i http://pypi.douban.com/simple --trusted-host pypi.douban.com && \
    pip3 install coloredlogs -i http://pypi.douban.com/simple --trusted-host pypi.douban.com && \
    pip3 install rsa -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

COPY quick-start/db_mgr.xml /opt/dble/conf/db.xml
COPY quick-start/user.xml /opt/dble/conf/
COPY quick-start/sharding.xml /opt/dble/conf/

COPY quick-start/*.cnf /opt/dble/conf/
COPY quick-start/docker_init_start.sh /opt/dble/bin/
COPY quick-start/start_mgr.sh /opt/dble/bin/
COPY wait-for-it.sh /opt/dble/bin/

RUN chmod 777 /opt/dble/bin/*

VOLUME /opt/dble

CMD ["/opt/dble/bin/docker_init_start.sh startMgr"]
